import { useState } from "react";
import { Link } from "react-router";
import { AlertTriangle, ArrowLeft, Check, Database, Flag, Loader2, Send, Sparkles, X } from "lucide-react";
import { Badge } from "../components/Badge";
import { useAuth } from "../auth/AuthProvider";
import { handleAIQuery, type AIRole } from "../services/aiService";

interface Message {
  id: number;
  type: "user" | "assistant";
  content: string;
  source?: "database" | "llm";
  warning?: boolean;
}

function describeAIError(error: unknown) {
  const message = error instanceof Error ? error.message : "";

  if (message.includes("429 Too Many Requests") || message.includes("Quota exceeded")) {
    return "Gemini is reachable, but this API key or project currently has no quota available for the configured model.";
  }

  if (message.includes("API key not valid") || message.includes("API_KEY_INVALID")) {
    return "Gemini rejected the configured API key. Check VITE_GEMINI_API_KEY in your local environment.";
  }

  if (message.includes("reported as leaked")) {
    return "Gemini blocked this API key because it was reported as leaked. Create a new key and update the local environment file.";
  }

  return "Something went wrong reaching the AI fallback. Please try again.";
}

function getSampleQuestions(role: AIRole) {
  if (role === "student") {
    return [
      "What is my GPA?",
      "What classes am I taking?",
      "What classes should I take?",
    ];
  }

  if (role === "instructor") {
    return [
      "How many students are enrolled?",
      "How do I post grades?",
      "Can I admit a waitlisted student?",
    ];
  }

  if (role === "registrar") {
    return [
      "Which semester phase allows class setup?",
      "What triggers student warnings?",
      "How do I approve graduation?",
    ];
  }

  return [
    "What courses does College0 offer?",
    "What are the graduation requirements?",
    "Where can I eat near CCNY?",
  ];
}

function AssistantAvatar() {
  return (
    <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-slate-800 text-xs font-semibold text-white">
      C0
    </div>
  );
}

function SourceBadge({ source }: { source?: Message["source"] }) {
  if (source === "database") {
    return (
      <Badge variant="success" className="gap-1.5 normal-case tracking-normal">
        <Database className="h-3 w-3" />
        Local DB
      </Badge>
    );
  }

  return (
    <Badge variant="warning" className="gap-1.5 normal-case tracking-normal">
      <Sparkles className="h-3 w-3" />
      AI generated
    </Badge>
  );
}

function FeedbackButtons() {
  const buttons = [
    { label: "Yes", icon: Check },
    { label: "No", icon: X },
    { label: "Flag response", icon: Flag },
  ];

  return (
    <div className="mt-3 flex flex-wrap items-center gap-2 text-xs text-slate-500">
      <span>Was this helpful?</span>
      {buttons.map(({ label, icon: Icon }) => (
        <button
          key={label}
          type="button"
          className="inline-flex h-8 items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 font-medium text-slate-700 shadow-sm transition-colors hover:border-slate-300 hover:bg-slate-50"
        >
          <Icon className="h-3.5 w-3.5" />
          {label}
        </button>
      ))}
    </div>
  );
}

function AssistantMessage({ message }: { message: Message }) {
  return (
    <div className="flex items-start gap-3">
      <AssistantAvatar />
      <div className="min-w-0 flex-1">
        <div className="max-w-[760px] rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm">
          <p className="whitespace-pre-wrap text-sm leading-6 text-slate-900">{message.content}</p>
          {message.source === "llm" && (
            <div className="mt-3 flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs leading-5 text-amber-900">
              <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-700" />
              <span>This answer was generated by AI and may be inaccurate or hallucinated. Verify important information before acting.</span>
            </div>
          )}
        </div>
        <div className="mt-2">
          <SourceBadge source={message.source} />
        </div>
        <FeedbackButtons />
      </div>
    </div>
  );
}

function UserMessage({ content }: { content: string }) {
  return (
    <div className="flex justify-end">
      <div className="max-w-[520px] rounded-2xl bg-slate-950 px-4 py-3 text-sm leading-6 text-white shadow-sm">
        {content}
      </div>
    </div>
  );
}

export function AIAssistant() {
  const { user } = useAuth();
  const role: AIRole = user?.role ?? "visitor";
  const backLink = user?.role === "instructor" ? "/instructor" : user?.role === "registrar" ? "/registrar" : user?.role === "student" ? "/student" : "/";
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 1,
      type: "assistant",
      content: "Hello. I can help with courses, registration, deadlines, program requirements, and general questions.",
      source: "database",
    },
  ]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const sampleQuestions = getSampleQuestions(role);

  const sendQuery = async (value = input) => {
    if (!value.trim() || loading) return;

    const query = value.trim();
    setInput("");
    setMessages((prev) => [...prev, { id: Date.now(), type: "user", content: query }]);
    setLoading(true);

    try {
      const result = await handleAIQuery(query, role, user?.email ?? "", user?.name ?? "Visitor");
      setMessages((prev) => [
        ...prev,
        {
          id: Date.now() + 1,
          type: "assistant",
          content: result.answer,
          source: result.source,
          warning: result.warning,
        },
      ]);
    } catch (error) {
      setMessages((prev) => [
        ...prev,
        {
          id: Date.now() + 1,
          type: "assistant",
          content: describeAIError(error),
          source: "llm",
          warning: true,
        },
      ]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={!user ? "min-h-screen bg-slate-50 px-4 py-5 md:px-6" : ""}>
      <div className={!user ? "mx-auto max-w-[1120px]" : "mx-auto max-w-[1120px]"}>
        <Link to={backLink} className="inline-flex items-center gap-2 text-sm font-medium text-blue-700 hover:text-blue-800">
          <ArrowLeft className="h-4 w-4" />
          Back to dashboard
        </Link>

        <div className="mt-3 flex flex-col gap-3 border-b border-slate-200 pb-5 md:flex-row md:items-end md:justify-between">
          <div>
            <h1 className="text-3xl text-slate-950">AI Assistant</h1>
            <p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">
              College0 checks local data first. Random questions use the AI fallback and are clearly marked for verification.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <SourceBadge source="database" />
            <SourceBadge source="llm" />
          </div>
        </div>

        <div className="mt-5 rounded-[28px] border border-slate-200 bg-slate-100/70 shadow-[0_18px_50px_-36px_rgba(15,23,42,0.45)]">
          <div className="h-[min(690px,calc(100vh-250px))] min-h-[520px] space-y-6 overflow-y-auto px-4 py-5 md:px-8">
            {messages.map((message) =>
              message.type === "user" ? (
                <UserMessage key={message.id} content={message.content} />
              ) : (
                <AssistantMessage key={message.id} message={message} />
              ),
            )}
            {loading && (
              <div className="flex items-start gap-3">
                <AssistantAvatar />
                <div className="inline-flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-500 shadow-sm">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Thinking...
                </div>
              </div>
            )}
          </div>

          <div className="border-t border-slate-200 bg-white/85 px-4 py-4 backdrop-blur md:px-8">
            <div className="mb-3 flex gap-2 overflow-x-auto pb-1">
              {sampleQuestions.map((question) => (
                <button
                  key={question}
                  type="button"
                  onClick={() => sendQuery(question)}
                  disabled={loading}
                  className="shrink-0 rounded-full border border-slate-200 bg-white px-3.5 py-2 text-xs font-medium text-slate-700 shadow-sm transition-colors hover:border-blue-200 hover:bg-blue-50 disabled:cursor-not-allowed disabled:opacity-50"
                >
                  {question}
                </button>
              ))}
            </div>

            <div className="flex items-center gap-3 rounded-full border border-slate-200 bg-white px-4 py-2 shadow-sm focus-within:border-blue-300 focus-within:ring-4 focus-within:ring-blue-100">
              <input
                type="text"
                value={input}
                onChange={(event) => setInput(event.target.value)}
                onKeyDown={(event) => event.key === "Enter" && sendQuery()}
                placeholder="Message College0 Assistant"
                disabled={loading}
                className="min-w-0 flex-1 bg-transparent py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none"
              />
              <button
                type="button"
                onClick={() => sendQuery()}
                disabled={loading || !input.trim()}
                className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-950 text-white transition-colors hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-45"
                aria-label="Send message"
              >
                {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
